# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c5e2c8076c2a50696e025927a58466fcad85fc180bf4522c43f57ff3798b0c0c91299a0b669d94e326f443320ef7abe90e54745d015acf91a56dc57f823bcc

test:
  secret_key_base: 9ea21ff0e3aa45dfeba7a5a78a8d7ebe254b6f2b7a3b7f7bc721436cda1b951040f67a916b80795c2ab673fbc9cb98a2331f3d99f2acec8d056b555666a32164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
